spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chandb
    username: chan
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  upload:
   dir: uploads
   url: http://localhost:8080/images